sonar.organization=tim-pohlmann
sonar.projectKey=Tim-Pohlmann_Dolphin
sonar.host.url=https://sonarcloud.io

sonar.sources=src/
sonar.tests=tests/
sonar.exclusions=**/obj/**,**/bin/**

sonar.cs.opencover.reportsPaths=tests/**/coverage.opencover.xml
